import { Icon } from "icon.slint";
import { Theme } from "theme.slint";

export component Example inherits Window {
    preferred-width: 480px;
    preferred-height: 160px;
    VerticalLayout {
        padding: 24px;
        alignment: start;
        spacing: 12px;
        Icon { name: "circle-check"; size: 16px; }
        Icon { name: "circle-x"; size: 16px; }
        Icon { name: "triangle-alert"; size: 16px; }
    }
}
