import { BarChart, ChartLegend } from "chart.slint";
import { Theme } from "theme.slint";

export component Example inherits Window {
    preferred-width: 480px;
    preferred-height: 360px;
    VerticalLayout {
        horizontal-stretch: 1;
        padding: Theme.page-padding(Theme.viewport);
        spacing: 12px;
        alignment: start;
        BarChart { horizontal-stretch: 1; points: [{ label: "my-plot", value: 24.0 }, { label: "band", value: 42.0 }, { label: "Title", value: 24.0 }, { label: "Series", value: 42.0 }, { label: "42", value: 24.0 }]; }
    }
}
