import { BarChart, ChartLegend } from "chart.slint";
import { Theme } from "theme.slint";

export component Example inherits Window {
    preferred-width: 480px;
    preferred-height: 360px;
    VerticalLayout {
        horizontal-stretch: 1;
        padding: Theme.page-padding(Theme.viewport);
        spacing: 12px;
        alignment: start;
        BarChart { horizontal-stretch: 1; points: [{ label: "Stock Price - Candlestick", value: 3.0 }, { label: "Stock Price - Line", value: 5.0 }, { label: "Trading Volume", value: 1000000.0 }]; }
    }
}
