import { Alert } from "alert.slint";
import { Theme, Status } from "theme.slint";

export component Example inherits Window {
    preferred-width: 480px;
    preferred-height: 280px;
    VerticalLayout {
        horizontal-stretch: 1;
        padding: Theme.page-padding(Theme.viewport);
        spacing: 12px;
        alignment: start;
        Alert { horizontal-stretch: 1; title: "Validation Failed"; message: "validation-error"; status: Status.info; }
    }
}
