import { Button } from "button.slint";
import { ButtonVariant, ControlSize } from "theme.slint";

export component Example inherits Window {
    preferred-width: 480px;
    preferred-height: 240px;
    VerticalLayout {
        padding: 24px;
        alignment: start;
        spacing: 8px;
        Button { text: "Extra Small"; size: ControlSize.xsmall; horizontal-stretch: 0; }
        Button { text: "Small"; size: ControlSize.small; horizontal-stretch: 0; }
        Button { text: "Medium"; horizontal-stretch: 0; }
        Button { text: "Large"; size: ControlSize.large; horizontal-stretch: 0; }
    }
}
