import { DatePicker } from "date-picker.slint";
import { Theme } from "theme.slint";

export component Example inherits Window {
    preferred-width: 480px;
    preferred-height: 280px;
    VerticalLayout {
        horizontal-stretch: 1;
        padding: Theme.page-padding(Theme.viewport);
        spacing: 12px;
        alignment: start;
        DatePicker { horizontal-stretch: 1; year: 2026; month: 9; day: 26; }
    }
}
