import { Pagination } from "pagination.slint";
import { Theme } from "theme.slint";

export component Example inherits Window {
    preferred-width: 480px;
    preferred-height: 280px;
    VerticalLayout {
        horizontal-stretch: 1;
        padding: Theme.page-padding(Theme.viewport);
        spacing: 12px;
        alignment: start;
        Pagination { horizontal-stretch: 0; page: 1; pages: 10; }
    }
}
