import { Select } from "select.slint";

export component Example inherits Window {
    preferred-width: 480px;
    preferred-height: 160px;
    VerticalLayout {
        padding: 24px;
        alignment: start;
        spacing: 8px;
        Select { placeholder: "Select"; items: [{ label: "Rust", value: "Rust" }, { label: "Go", value: "Go" }, { label: "JavaScript", value: "JavaScript" }, { label: "Select a language...", value: "Select a language..." }]; horizontal-stretch: 1; }
    }
}
