import { Select } from "select.slint";

export component Example inherits Window {
    preferred-width: 480px;
    preferred-height: 160px;
    VerticalLayout {
        padding: 24px;
        alignment: start;
        spacing: 8px;
        Select { placeholder: "Select"; items: [{ label: "Apple", value: "Apple" }, { label: "Orange", value: "Orange" }, { label: "Banana", value: "Banana" }, { label: "Grape", value: "Grape" }]; horizontal-stretch: 1; }
    }
}
