import { Select } from "select.slint";

export component Example inherits Window {
    preferred-width: 480px;
    preferred-height: 160px;
    VerticalLayout {
        padding: 24px;
        alignment: start;
        spacing: 8px;
        Select { placeholder: "Select"; items: [{ label: "Selected: {:?}", value: "Selected: {:?}" }, { label: "Selection cleared", value: "Selection cleared" }]; horizontal-stretch: 1; }
    }
}
