import { Select } from "select.slint";

export component Example inherits Window {
    preferred-width: 480px;
    preferred-height: 160px;
    VerticalLayout {
        padding: 24px;
        alignment: start;
        spacing: 8px;
        Select { placeholder: "Select"; items: [{ label: "New Option 1", value: "New Option 1" }, { label: "New Option 2", value: "New Option 2" }]; horizontal-stretch: 1; }
    }
}
