use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let catalog_path = manifest_dir.join("ui/gallery-catalog.slint");
    let catalog = render_catalog(&manifest_dir.join("ui/examples"));
    match fs::read_to_string(&catalog_path) {
        Ok(current) if current == catalog => {}
        _ => fs::write(&catalog_path, catalog).expect("write gallery catalog"),
    }
    slint_build::compile(manifest_dir.join("ui/gallery.slint"))
        .expect("Slint gallery should compile");
}

struct Page {
    slug: String,
    name: String,
}

/// Slint components are distinct types, so the gallery cannot loop over pages.
/// The example directory is the list: every `*Example` export becomes one branch.
fn render_catalog(examples: &Path) -> String {
    let mut pages = Vec::new();
    for entry in fs::read_dir(examples).expect("read ui/examples") {
        let path = entry.expect("read example entry").path();
        if path.extension().and_then(|ext| ext.to_str()) != Some("slint") {
            continue;
        }
        let source = fs::read_to_string(&path).expect("read example");
        let Some(name) = exported_example(&source) else {
            continue;
        };
        let slug = path
            .file_stem()
            .expect("example file name")
            .to_string_lossy()
            .into_owned();
        pages.push(Page { slug, name });
    }
    pages.sort_by(|a, b| a.slug.cmp(&b.slug));

    let mut out = String::from(
        "// Generated by build.rs from ui/examples/*.slint. Do not edit.\n\
         // Each page is a separate component type, so the gallery selects it\n\
         // with one branch. Adding an example file adds the branch.\n\n",
    );
    for page in &pages {
        out.push_str(&format!(
            "import {{ {name} }} from \"examples/{slug}.slint\";\n",
            name = page.name,
            slug = page.slug,
        ));
    }
    out.push_str(
        "\nexport component GalleryCatalog inherits VerticalLayout {\n    \
         in property <string> component;\n    \
         alignment: start;\n\n",
    );
    for page in &pages {
        out.push_str(&format!(
            "    if component == \"{slug}\": {name} {{ }}\n",
            slug = page.slug,
            name = page.name,
        ));
    }
    out.push_str("}\n");
    out
}

fn exported_example(source: &str) -> Option<String> {
    for line in source.lines() {
        let Some(rest) = line.trim().strip_prefix("export component ") else {
            continue;
        };
        let name = rest.split_whitespace().next().unwrap_or("");
        if name.ends_with("Example") {
            return Some(name.to_string());
        }
    }
    None
}
