import { Carousel } from "carousel.slint";
import { Theme } from "theme.slint";
export component Example inherits Window {
    preferred-width: 520px;
    preferred-height: 440px;
    VerticalLayout {
        horizontal-stretch: 1;
        padding: Theme.page-padding(Theme.viewport);
        spacing: 12px;
        alignment: center;
        Carousel {
            previous-text: "Back";
            next-text: "Forward";
            count: 3;
        }
    }
}
