import { Kbd, KbdSequence } from "kbd.slint";
import { Theme } from "theme.slint";

export component Example inherits Window {
    preferred-width: 480px;
    preferred-height: 280px;
    VerticalLayout {
        horizontal-stretch: 1;
        padding: Theme.page-padding(Theme.viewport);
        spacing: 12px;
        alignment: start;
        KbdSequence {
            Kbd { text: "left";  horizontal-stretch: 0; }
        Kbd { text: "right";  horizontal-stretch: 0; }
        Kbd { text: "up";  horizontal-stretch: 0; }
        Kbd { text: "down";  horizontal-stretch: 0; }
        }
    }
}
