import { Plot } from "plot.slint";
import { Theme } from "theme.slint";

export component Example inherits Window {
    preferred-width: 480px;
    preferred-height: 360px;
    VerticalLayout {
        horizontal-stretch: 1;
        padding: Theme.page-padding(Theme.viewport);
        spacing: 12px;
        alignment: start;
        Plot { horizontal-stretch: 1; points: [{ label: "series1", value: 4.0 }, { label: "series2", value: 8.0 }, { label: "series1", value: 6.0 }, { label: "series2", value: 4.0 }]; x-label: "X"; y-label: "Y"; }
    }
}
