import { Plot } from "plot.slint";
import { Theme } from "theme.slint";

export component Example inherits Window {
    preferred-width: 480px;
    preferred-height: 360px;
    VerticalLayout {
        horizontal-stretch: 1;
        padding: Theme.page-padding(Theme.viewport);
        spacing: 12px;
        alignment: start;
        Plot { horizontal-stretch: 1; points: [{ label: "desktop", value: 1.0 }, { label: "mobile", value: 0.0 }, { label: "desktop", value: 0.0 }, { label: "mobile", value: 0.0 }]; x-label: "X"; y-label: "Y"; }
    }
}
