import { Theme } from "../theme.slint";
import { GroupBox, GroupBoxVariant } from "../group-box.slint";
import { Calendar } from "../calendar.slint";

export component CalendarExample inherits VerticalLayout {
    padding: 24px;
    spacing: 24px;
    alignment: start;

    GroupBox { title: "September 2026"; variant: GroupBoxVariant.outline;
        Calendar { year: 2026; month: 9; selected-day: 26; }
    }

}
