import { Theme } from "../theme.slint";
import { GroupBox } from "section.slint";
import { Calendar } from "../calendar.slint";

export component CalendarExample inherits VerticalLayout {
    horizontal-stretch: 1;
    padding: Theme.page-padding(Theme.viewport);
    spacing: 24px;
    alignment: start;

    GroupBox {
        title: "Calendar";
        Calendar { year: 2026; month: 9; selected-day: 26; }
    }

    GroupBox {
        title: "Two columns";
        Calendar { year: 2026; month: 9; selected-day: 26; columns: 2; }
    }

    GroupBox {
        title: "Three columns";
        Calendar { year: 2026; month: 9; selected-day: 26; columns: 3; }
    }
}
