import { Theme } from "../theme.slint";
import { GroupBox, GroupBoxVariant } from "section.slint";
import { Combobox } from "../combobox.slint";

export component ComboboxExample inherits VerticalLayout {
    horizontal-stretch: 1;
    padding: Theme.page-padding(Theme.viewport);
    spacing: 24px;
    alignment: start;

    Combobox {
        items: [
            { label: "Button", value: "button" },
            { label: "Input", value: "input" },
            { label: "Dialog", value: "dialog" },
        ];
    }

}
