import { Theme, ControlSize } from "../theme.slint";
import { GroupBox, GroupBoxVariant } from "section.slint";
import { DatePicker } from "../date-picker.slint";

export component DatePickerExample inherits VerticalLayout {
    horizontal-stretch: 1;
    padding: Theme.page-padding(Theme.viewport);
    spacing: 24px;
    alignment: start;

    GroupBox {
        title: "Date";
        variant: GroupBoxVariant.outline;
        DatePicker {}
    }

    GroupBox {
        title: "Different Sizes";
        variant: GroupBoxVariant.outline;
        DatePicker {
            size: ControlSize.small;
        }
        DatePicker {}
        DatePicker {
            size: ControlSize.large;
        }
    }

}
