import { Theme } from "../theme.slint";
import { GroupBox, GroupBoxVariant } from "section.slint";
import { Dock } from "../dock.slint";
import { List } from "../list.slint";

export component DockExample inherits VerticalLayout {
    horizontal-stretch: 1;
    padding: Theme.page-padding(Theme.viewport);
    spacing: 24px;
    alignment: start;

    Dock {
        height: 280px;
        tabs: [{ title: "main.rs" }, { title: "lib.rs" }];
        List {
            items: [
                { title: "src", description: "", icon: "folder" },
                { title: "Cargo.toml", description: "", icon: "file" },
            ];
        }
    }

}
