import { Theme } from "../theme.slint";
import { GroupBox, GroupBoxVariant } from "section.slint";
import { Editor } from "../editor.slint";

export component EditorExample inherits VerticalLayout {
    horizontal-stretch: 1;
    padding: Theme.page-padding(Theme.viewport);
    spacing: 24px;
    alignment: start;

    Editor {
        height: 200px;
        text: "fn main() {\n    println!(\"hello\");\n}\n";
    }

}
