import { Theme } from "../theme.slint";
import { GroupBox, GroupBoxVariant } from "section.slint";
import { HoverCard } from "../hover-card.slint";
import { ButtonVariant } from "../theme.slint";
import { Button } from "../button.slint";

export component HoverCardExample inherits VerticalLayout {
    horizontal-stretch: 1;
    padding: Theme.page-padding(Theme.viewport);
    spacing: 24px;
    alignment: start;

    GroupBox { title: "Hover"; variant: GroupBoxVariant.outline;
        HoverCard {
            title: "Ada Lovelace";
            description: "Mathematician and the first computer programmer.";
            Button { text: "@ada"; variant: ButtonVariant.link; }
        }
    }

}
