import { Theme } from "../theme.slint";
import { GroupBox, GroupBoxVariant } from "../group-box.slint";
import { Icon } from "../icon.slint";

export component IconExample inherits VerticalLayout {
    private property <int> wrap-cols: Theme.wrap-columns(Theme.viewport);
    padding: Theme.page-padding(Theme.viewport);
    spacing: 24px;
    alignment: start;

    GroupBox { title: "Icons"; variant: GroupBoxVariant.outline;
        GridLayout { spacing: 12px;
            Icon {
                row: Theme.wrap-row(0, root.wrap-cols);
                col: Theme.wrap-col(0, root.wrap-cols);
                horizontal-stretch: 0;
                 name: "search"; }
            Icon {
                row: Theme.wrap-row(1, root.wrap-cols);
                col: Theme.wrap-col(1, root.wrap-cols);
                horizontal-stretch: 0;
                 name: "settings"; }
            Icon {
                row: Theme.wrap-row(2, root.wrap-cols);
                col: Theme.wrap-col(2, root.wrap-cols);
                horizontal-stretch: 0;
                 name: "star"; color: Theme.warning; }
            Icon {
                row: Theme.wrap-row(3, root.wrap-cols);
                col: Theme.wrap-col(3, root.wrap-cols);
                horizontal-stretch: 0;
                 name: "loader-circle"; spinning: true; }
        
            Rectangle {
                row: 0;
                col: root.wrap-cols;
                horizontal-stretch: 1;
            }
}
    }

}
