import { Theme } from "../theme.slint";
import { GroupBox, GroupBoxVariant } from "section.slint";
import { ImageView } from "../image.slint";

export component ImageExample inherits VerticalLayout {
    horizontal-stretch: 1;
    padding: Theme.page-padding(Theme.viewport);
    spacing: 24px;
    alignment: start;

    GroupBox {
        title: "Placeholder";
        variant: GroupBoxVariant.outline;
        ImageView {
            height: 160px;
        }
    }

}
