import { Theme } from "../theme.slint";
import { GroupBox, GroupBoxVariant } from "section.slint";
import { InputGroup, InputGroupAddon } from "../input-group.slint";
import { Input } from "../input.slint";
import { ButtonVariant } from "../theme.slint";
import { Button } from "../button.slint";

export component InputGroupExample inherits VerticalLayout {
    horizontal-stretch: 1;
    padding: Theme.page-padding(Theme.viewport);
    spacing: 24px;
    alignment: start;

    GroupBox { title: "Search"; variant: GroupBoxVariant.outline;
        InputGroup {
            Input { placeholder: "Search the docs…"; appearance: false; prefix-icon: "search"; }
            Button { text: "Search"; variant: ButtonVariant.primary; }
        }
    }

}
