import { Theme } from "../theme.slint";
import { GroupBox, GroupBoxVariant } from "section.slint";
import { Kbd, KbdSequence } from "../kbd.slint";

export component KbdExample inherits VerticalLayout {
    horizontal-stretch: 1;
    padding: Theme.page-padding(Theme.viewport);
    spacing: 24px;
    alignment: start;

    GroupBox {
        title: "Shortcuts";
        variant: GroupBoxVariant.outline;
        KbdSequence {
            Kbd {
                text: "⌘";
            }
            Kbd {
                text: "K";
            }
        }
        KbdSequence {
            Kbd {
                text: "Ctrl";
            }
            Kbd {
                text: "Shift";
            }
            Kbd {
                text: "P";
            }
        }
    }

}
