import { Theme, ControlSize } from "../theme.slint";
import { GroupBox, GroupBoxVariant } from "section.slint";
import { Label } from "../label.slint";
import { Input } from "../input.slint";

export component LabelExample inherits VerticalLayout {
    horizontal-stretch: 1;
    padding: Theme.page-padding(Theme.viewport);
    spacing: 24px;
    alignment: start;

    GroupBox {
        title: "Form labels";
        variant: GroupBoxVariant.outline;
        Label {
            text: "Email";
            required: true;
        }
        Input {
            placeholder: "you@example.com";
        }
    }

    GroupBox {
        title: "Different Sizes";
        variant: GroupBoxVariant.outline;
        Label {
            text: "Small";
            size: ControlSize.small;
        }
        Label {
            text: "Medium";
        }
        Label {
            text: "Large";
            size: ControlSize.large;
            required: true;
        }
    }

}
