import { Theme } from "../theme.slint";
import { GroupBox, GroupBoxVariant } from "section.slint";
import { Pagination } from "../pagination.slint";

export component PaginationExample inherits VerticalLayout {
    horizontal-stretch: 1;
    padding: Theme.page-padding(Theme.viewport);
    spacing: 24px;
    alignment: start;

    GroupBox {
        title: "Pages";
        variant: GroupBoxVariant.outline;
        Pagination {
            pages: 12;
            page: 1;
        }
    }

}
