import { Theme, ControlSize } from "../theme.slint";
import { GroupBox, GroupBoxVariant } from "section.slint";
import { Pagination } from "../pagination.slint";

export component PaginationExample inherits VerticalLayout {
    horizontal-stretch: 1;
    padding: Theme.page-padding(Theme.viewport);
    spacing: 24px;
    alignment: start;

    GroupBox {
        title: "Pages";
        variant: GroupBoxVariant.outline;
        Pagination {
            pages: 12;
            page: 1;
        }
    }

    GroupBox {
        title: "Different Sizes";
        variant: GroupBoxVariant.outline;
        Pagination {
            pages: 8;
            page: 2;
            size: ControlSize.xsmall;
        }
        Pagination {
            pages: 8;
            page: 3;
            size: ControlSize.medium;
        }
        Pagination {
            pages: 8;
            page: 4;
            size: ControlSize.large;
        }
    }

}
