import { Theme } from "../theme.slint";
import { GroupBox, GroupBoxVariant } from "section.slint";
import { Popover } from "../popover.slint";
import { Button } from "../button.slint";

export component PopoverExample inherits VerticalLayout {
    horizontal-stretch: 1;
    padding: Theme.page-padding(Theme.viewport);
    spacing: 24px;
    alignment: start;

    GroupBox { title: "Click"; variant: GroupBoxVariant.outline;
        Popover {
            Button { text: "Open popover"; }
        }
    }

}
