import { Theme } from "../theme.slint";
import { GroupBox, GroupBoxVariant } from "../group-box.slint";
import { Resizable } from "../resizable.slint";

export component ResizableExample inherits VerticalLayout {
    horizontal-stretch: 1;
    padding: Theme.page-padding(Theme.viewport);
    spacing: 24px;
    alignment: start;

    Resizable {
        height: 200px;
        Text { text: "Left pane"; color: Theme.foreground; }
    }

}
