import { Theme } from "../theme.slint";
import { GroupBox, GroupBoxVariant } from "section.slint";
import { Skeleton } from "../skeleton.slint";

export component SkeletonExample inherits VerticalLayout {
    horizontal-stretch: 1;
    padding: Theme.page-padding(Theme.viewport);
    spacing: 24px;
    alignment: start;

    GroupBox {
        title: "Loading";
        variant: GroupBoxVariant.outline;
        Skeleton {
            height: 16px;
        }
        Skeleton {
            height: 16px;
            width: 70%;
        }
        Skeleton {
            height: 80px;
        }
    }

    GroupBox {
        title: "Circle Skeleton";
        variant: GroupBoxVariant.outline;
        Skeleton {
            width: 48px;
            height: 48px;
            radius: 24px;
        }
    }

    GroupBox {
        title: "Different Shapes";
        variant: GroupBoxVariant.outline;
        Skeleton {
            height: 12px;
            radius: 2px;
        }
        Skeleton {
            width: 160px;
            height: 40px;
            radius: 8px;
        }
        Skeleton {
            width: 48px;
            height: 48px;
            radius: 24px;
        }
    }

}
