import { Theme } from "../theme.slint";
import { GroupBox, GroupBoxVariant } from "section.slint";
import { Slider } from "../slider.slint";

export component SliderExample inherits VerticalLayout {
    horizontal-stretch: 1;
    padding: Theme.page-padding(Theme.viewport);
    spacing: 24px;
    alignment: start;

    private property <float> volume: 42;
    GroupBox {
        title: "Volume";
        variant: GroupBoxVariant.outline;
        Slider {
            value <=> root.volume;
        }
        Text {
            text: "\{round(root.volume)}%";
            color: Theme.muted-foreground;
        }
    }

}
