import { Theme } from "../theme.slint";
import { GroupBox, GroupBoxVariant } from "../group-box.slint";
import { Textarea } from "../textarea.slint";

export component TextareaExample inherits VerticalLayout {
    padding: 24px;
    spacing: 24px;
    alignment: start;

    GroupBox { title: "Bio"; variant: GroupBoxVariant.outline;
        Textarea { placeholder: "Tell us about yourself…"; }
    }

}
