import { Theme } from "../theme.slint";
import { GroupBox, GroupBoxVariant } from "section.slint";
import { Textarea } from "../textarea.slint";

export component TextareaExample inherits VerticalLayout {
    horizontal-stretch: 1;
    padding: Theme.page-padding(Theme.viewport);
    spacing: 24px;
    alignment: start;

    GroupBox {
        title: "Bio";
        variant: GroupBoxVariant.outline;
        Textarea {
            placeholder: "Tell us about yourself…";
        }
    }

}
