import { Theme, ControlSize } from "../theme.slint";
import { GroupBox, GroupBoxVariant } from "section.slint";
import { Toggle, ToggleGroup } from "../toggle.slint";

export component ToggleExample inherits VerticalLayout {
    horizontal-stretch: 1;
    private property <int> wrap-cols: Theme.wrap-columns(Theme.viewport);
    padding: Theme.page-padding(Theme.viewport);
    spacing: 24px;
    alignment: start;

    GroupBox {
        title: "Toggle";
        variant: GroupBoxVariant.outline;
        GridLayout {
            spacing: 8px;
            Toggle {
                row: Theme.wrap-row(0, root.wrap-cols);
                col: Theme.wrap-col(0, root.wrap-cols);
                horizontal-stretch: 0;
                icon: "bold";
            }
            Toggle {
                row: Theme.wrap-row(1, root.wrap-cols);
                col: Theme.wrap-col(1, root.wrap-cols);
                horizontal-stretch: 0;
                icon: "italic";
                selected: true;
            }
            Toggle {
                row: Theme.wrap-row(2, root.wrap-cols);
                col: Theme.wrap-col(2, root.wrap-cols);
                horizontal-stretch: 0;
                icon: "underline";
            }
            Rectangle {
                row: 0;
                col: root.wrap-cols;
                horizontal-stretch: 1;
            }
        }
    }
    GroupBox {
        title: "Group";
        variant: GroupBoxVariant.outline;
        ToggleGroup {
            options: [
                { text: "Day", icon: "sun" },
                { text: "Week", icon: "" },
                { text: "Month", icon: "" }
            ];
        }
    }

    GroupBox {
        title: "Different Sizes";
        variant: GroupBoxVariant.outline;
        Toggle {
            text: "Small";
            size: ControlSize.small;
            selected: true;
        }
        Toggle {
            text: "Medium";
            selected: true;
        }
        Toggle {
            text: "Large";
            size: ControlSize.large;
            selected: true;
        }
    }

    GroupBox {
        title: "Disabled State";
        variant: GroupBoxVariant.outline;
        Toggle {
            text: "Disabled";
            enabled: false;
        }
        Toggle {
            text: "Disabled on";
            enabled: false;
            selected: true;
        }
    }

}
