import { Theme } from "../theme.slint";
import { GroupBox, GroupBoxVariant } from "section.slint";
import { Tooltip } from "../tooltip.slint";
import { Button } from "../button.slint";

export component TooltipExample inherits VerticalLayout {
    horizontal-stretch: 1;
    padding: Theme.page-padding(Theme.viewport);
    spacing: 24px;
    alignment: start;

    GroupBox { title: "Hover the button"; variant: GroupBoxVariant.outline;
        Tooltip {
            text: "Create a new document";
            Button { text: "New file"; icon: "file"; }
        }
    }

}
