import { Theme } from "../theme.slint";
import { GroupBox, GroupBoxVariant } from "../group-box.slint";
import { Tree } from "../tree.slint";

export component TreeExample inherits VerticalLayout {
    horizontal-stretch: 1;
    padding: Theme.page-padding(Theme.viewport);
    spacing: 24px;
    alignment: start;

    Tree {
        items: [
            { label: "src", depth: 0, folder: true, expanded: true },
            { label: "lib.rs", depth: 1, folder: false, expanded: false },
            { label: "main.rs", depth: 1, folder: false, expanded: false },
            { label: "ui", depth: 0, folder: true, expanded: false },
        ];
    }

}
