import { Select } from "select.slint";

export component Example inherits Window {
    preferred-width: 480px;
    preferred-height: 160px;
    VerticalLayout {
        padding: 24px;
        alignment: start;
        spacing: 8px;
        Select { placeholder: "Select"; items: [{ label: "{} ({})", value: "{} ({})" }, { label: "United States", value: "United States" }, { label: "US", value: "US" }, { label: "Canada", value: "Canada" }]; horizontal-stretch: 1; }
    }
}
