import { List } from "list.slint";
import { Theme } from "theme.slint";

export component Example inherits Window {
    preferred-width: 480px;
    preferred-height: 280px;
    VerticalLayout {
        horizontal-stretch: 1;
        padding: Theme.page-padding(Theme.viewport);
        spacing: 12px;
        alignment: start;
        List { horizontal-stretch: 1; items: [{ title: "Item 1", description: "Item 2", icon: "" }, { title: "Item 2", description: "Item 3", icon: "" }, { title: "Item 3", description: "", icon: "" }]; }
    }
}
