import { Rating } from "rating.slint";
import { Theme, ControlSize } from "theme.slint";

export component Example inherits Window {
    preferred-width: 480px;
    preferred-height: 280px;
    VerticalLayout {
        horizontal-stretch: 1;
        padding: Theme.page-padding(Theme.viewport);
        spacing: 12px;
        alignment: start;
        Rating { horizontal-stretch: 0; value: 3; size: ControlSize.xsmall; }
    }
}
