import { TextView, TextHeading, TextParagraph } from "text-view.slint";
import { Theme } from "theme.slint";

export component Example inherits Window {
    preferred-width: 480px;
    preferred-height: 280px;
    VerticalLayout {
        horizontal-stretch: 1;
        padding: Theme.page-padding(Theme.viewport);
        spacing: 12px;
        alignment: start;
        TextView {
            horizontal-stretch: 1;
            TextHeading { text: "ticker"; level: 2; }
            TextParagraph { text: "ticker"; }
        }
    }
}
