import { Button } from "button.slint";
import { Dialog, DialogFooter } from "dialog.slint";

export component Example inherits Window {
    preferred-width: 480px;
    preferred-height: 360px;
    private property <bool> open;

    VerticalLayout {
        padding: 24px;
        alignment: start;
        Button {
            text: "Show Information";
            clicked => { root.open = true; }
        }
    }

    Dialog {
        width: 100%;
        height: 100%;
        open <=> root.open;
        show-close: true;
        title: "Information";
        description: "Some information you can dismiss with the close button.";
        DialogFooter {
            centered: true;
            Button {
                text: "OK";
                clicked => { root.open = false; }
            }
        }
    }
}
