import { Calendar } from "calendar.slint";
import { Theme } from "theme.slint";

export component Example inherits Window {
    preferred-width: 480px;
    preferred-height: 360px;
    VerticalLayout {
        horizontal-stretch: 1;
        padding: Theme.page-padding(Theme.viewport);
        spacing: 12px;
        alignment: start;
        Calendar { horizontal-stretch: 1; year: 2026; month: 9; selected-day: 26; }
    }
}
